server:
  port: 8091
spring:
  # H2 specific
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    userName: sa
  #    password: ''
  #  h2:
  #    console:
  #      enabled: true
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    database-platform: org.hibernate.dialect.H2Dialect

  # MYSQL
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
      #rabbitmq:
      # host: "localhost"
      #port: 5672
    #username: "guest"
    #password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"